services:
  helpdesk:
    build: .
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: ${NODE_ENV}
      NITRO_PORT: ${PORT}
      NUXT_PUBLIC_API_URL: ${API_URL}
      NUXT_PUBLIC_SOCKET_URL: ${SOCKET_URL}
      NUXT_API_URL: ${API_URL}
